import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


def visual_mat(matr):
    matr = matr.dropna(how='any')
    sns.set_style('whitegrid')
    data = matr.groupby(by='ÁREA DE CONOCIMIENTO')['MATRICULADOS'].count()
    plt.barh(y=data.index, width=data.values)
    plt.title('Estudiantes matriculados por Área de Conocimiento')
    plt.xlabel('Estudiantes matriculados')
    plt.ylabel('Área de Conocimiento')
    plt.show()
    data = matr.groupby(by='DEPARTAMENTO DE OFERTA DEL PROGRAMA')['MATRICULADOS'].count()
    plt.barh(y=data.index, width=data.values)
    plt.title('Estudiantes matriculados por departamento de oferta del programa')
    plt.xlabel('Estudiantes matriculados')
    plt.ylabel('Departamento de oferta')
    plt.show()
    data = matr.groupby(by='DESC CINE CAMPO AMPLIO')['MATRICULADOS'].count()
    plt.barh(y=data.index, width=data.values)
    plt.title('Estudiantes matriculados por campo de estudio')
    plt.xlabel('Estudiantes matriculados')
    plt.ylabel('Campo de estudio')
    plt.show()
    data = matr.groupby(by='SEXO')['MATRICULADOS'].count()
    plt.barh(y=data.index, width=data.values)
    plt.title('Estudiantes matriculados por genero')
    plt.xlabel('Estudiantes matriculados')
    plt.ylabel('Genero')
    plt.show()

def visual_admi(admi):
    admi = admi.dropna(how='any')
    sns.set_style('whitegrid')
    data = admi.groupby(by='ÁREA DE CONOCIMIENTO')['ADMITIDOS'].count()    
    plt.barh(y=data.index, width=data.values)
    plt.title('Estudiantes Admitidos por Área de Conocimiento')
    plt.xlabel('Admitidos en miles')
    plt.ylabel('Área de Conocimiento')
    plt.show()
    data = admi.groupby(by='DEPARTAMENTO DE OFERTA DEL PROGRAMA')['ADMITIDOS'].count()
    plt.barh(y=data.index, width=data.values)
    plt.title('Estudiantes Admitidos por departamento de oferta del programa')
    plt.xlabel('Admitidos en miles')
    plt.ylabel('Departamento de oferta')
    plt.show()
    data = admi.groupby(by='DESC CINE CAMPO AMPLIO')['ADMITIDOS'].count()
    plt.barh(y=data.index, width=data.values)
    plt.title('Estudiantes matriculados por campo de estudio')
    plt.xlabel('Estudiantes matriculados')
    plt.ylabel('Campo de estudio')
    plt.show()
    data = admi.groupby(by='SEXO')['ADMITIDOS'].count()
    sns.set_style('whitegrid')
    plt.barh(y=data.index, width=data.values)
    plt.title('Estudiantes Admitidos por genero')
    plt.xlabel('Admitidos en miles')
    plt.ylabel('Genero')
    plt.show()

def visual_prim(prim):
    prim = prim.dropna(how='any')
    sns.set_style('whitegrid')
    data = prim.groupby(by='ÁREA DE CONOCIMIENTO')['MATRICULADOS PRIMER CURSO'].count()
    plt.barh(y=data.index, width=data.values)
    plt.title('Estudiantes en primer curso por Área de Conocimiento')
    plt.xlabel('Matriculados en primer curso')
    plt.ylabel('Área de Conocimiento')
    plt.show()
    data = prim.groupby(by='DEPARTAMENTO DE OFERTA DEL PROGRAMA')['MATRICULADOS PRIMER CURSO'].count()
    plt.barh(y=data.index, width=data.values)
    plt.title('Estudiantes en primer curso por departamento de oferta del programa')
    plt.xlabel('Matriculados en primer curso')
    plt.ylabel('Departamento de oferta')
    plt.show()
    data = prim.groupby(by='DESC CINE CAMPO AMPLIO')['MATRICULADOS PRIMER CURSO'].count()
    plt.barh(y=data.index, width=data.values)
    plt.title('Estudiantes en primer curso por campo de estudio')
    plt.xlabel('Matriculados en primer curso')
    plt.ylabel('Campo de estudio')
    plt.show()
    data = prim.groupby(by='SEXO')['MATRICULADOS PRIMER CURSO'].count()
    plt.barh(y=data.index, width=data.values)
    plt.title('Estudiantes en primer curso por genero')
    plt.xlabel('Matriculados en primer curso')
    plt.ylabel('Genero')
    plt.show()

def visual_grad(grad):
    grad = grad.dropna(how='any')
    sns.set_style('whitegrid')
    data = grad.groupby(by='ÁREA DE CONOCIMIENTO')['GRADUADOS'].count()
    plt.barh(y=data.index, width=data.values)
    plt.title('Estudiantes graduados por Área de Conocimiento')
    plt.xlabel('Graduados')
    plt.ylabel('Área de Conocimiento')
    plt.show()
    data = grad.groupby(by='DEPARTAMENTO DE OFERTA DEL PROGRAMA')['GRADUADOS'].count()
    plt.barh(y=data.index, width=data.values)
    plt.title('Estudiantes graduados por Área de Conocimiento')
    plt.xlabel('Graduados')
    plt.ylabel('Área de Conocimiento')
    plt.show()
    data = grad.groupby(by='DESC CINE CAMPO AMPLIO')['GRADUADOS'].count()
    plt.barh(y=data.index, width=data.values)
    plt.title('Estudiantes graduados por Área de Conocimiento')
    plt.xlabel('Graduados')
    plt.ylabel('Área de Conocimiento')
    plt.show()
    data = grad.groupby(by='SEXO')['GRADUADOS'].count()
    plt.barh(y=data.index, width=data.values)
    plt.title('Estudiantes graduados por Área de Conocimiento')
    plt.xlabel('Graduados')
    plt.ylabel('Área de Conocimiento')
    plt.show()